package com.toyota.showcase.model

import android.os.Parcelable
import com.toyota.showcase.R
import kotlinx.parcelize.Parcelize

@Parcelize
data class ToyotaCar(
    val id: Int,
    val name: String,
    val image: Int,
    val price: String,
    val topTrim: String,
    val lease: String,
    val engine: String,
    val transmission: String,
    val acceleration: String,
    val torque: String,
    val fuelEfficiency: String,
    val fuelTank: String,
    val dimensions: String,
    val groundClearance: String,
    val seating: String,
    val cargo: String,
    val driveType: String,
    val suspension: String,
    val brakes: String,
    val wheels: String,
    val infotainment: String,
    val audio: String,
    val interior: String,
    val safety: String,
    val warranty: String
) : Parcelable {
    companion object {
        fun getSampleCars(): List<ToyotaCar> {
            return listOf(
                ToyotaCar(
                    id = 1,
                    name = "2024 Toyota Camry",
                    image = R.drawable.toyota_camry_xse,
                    price = "Starting at $26,420",
                    topTrim = "XSE V6 from $36,395",
                    lease = "$299/month for 36 months",
                    engine = "2.5L Dynamic Force 4-cylinder",
                    transmission = "8-speed automatic transmission",
                    acceleration = "0-60 mph in 7.6 seconds",
                    torque = "184 lb-ft @ 5,000 rpm",
                    fuelEfficiency = "28 city / 39 highway MPG",
                    fuelTank = "15.8 gallon fuel tank",
                    dimensions = "192.1\" L x 72.4\" W x 56.9\" H",
                    groundClearance = "5.7 inches",
                    seating = "5 passengers",
                    cargo = "15.1 cubic feet",
                    driveType = "Front-Wheel Drive (FWD)",
                    suspension = "Sport-tuned independent MacPherson strut",
                    brakes = "Power-assisted ventilated disc brakes",
                    wheels = "19-inch alloy wheels",
                    infotainment = "9-inch touchscreen with Apple CarPlay",
                    audio = "JBL Premium Audio with 9 speakers",
                    interior = "Leather-trimmed seats, dual-zone climate control",
                    safety = "Toyota Safety Sense 2.5+",
                    warranty = "36-month/36,000-mile basic warranty"
                ),
                ToyotaCar(
                    id = 2,
                    name = "2024 Toyota RAV4",
                    image = R.drawable.toyota_rav4_adventure,
                    price = "Starting at $28,475",
                    topTrim = "TRD Off-Road from $37,195",
                    lease = "$319/month for 36 months",
                    engine = "2.5L Dynamic Force 4-cylinder",
                    transmission = "8-speed automatic transmission",
                    acceleration = "0-60 mph in 8.0 seconds",
                    torque = "184 lb-ft @ 5,000 rpm",
                    fuelEfficiency = "27 city / 35 highway MPG",
                    fuelTank = "14.5 gallon fuel tank",
                    dimensions = "180.9\" L x 73.0\" W x 67.0\" H",
                    groundClearance = "8.6 inches",
                    seating = "5 passengers",
                    cargo = "37.6 cubic feet",
                    driveType = "Dynamic Torque Vectoring AWD",
                    suspension = "Multi-link rear suspension",
                    brakes = "Power-assisted ventilated disc brakes",
                    wheels = "19-inch TRD alloy wheels",
                    infotainment = "10.5-inch touchscreen with Apple CarPlay",
                    audio = "JBL Premium Audio with 11 speakers",
                    interior = "SofTex®-trimmed seats, dual-zone climate control",
                    safety = "Toyota Safety Sense 2.5",
                    warranty = "36-month/36,000-mile basic warranty"
                ),
                ToyotaCar(
                    id = 3,
                    name = "2024 Toyota Highlander",
                    image = R.drawable.toyota_highlander_platinum,
                    price = "Starting at $36,620",
                    topTrim = "Platinum from $49,075",
                    lease = "$389/month for 36 months",
                    engine = "2.4L turbocharged 4-cylinder",
                    transmission = "8-speed automatic transmission",
                    acceleration = "0-60 mph in 7.3 seconds",
                    torque = "310 lb-ft @ 2,000 rpm",
                    fuelEfficiency = "22 city / 29 highway MPG",
                    fuelTank = "17.9 gallon fuel tank",
                    dimensions = "194.9\" L x 76.0\" W x 68.1\" H",
                    groundClearance = "8.0 inches",
                    seating = "7-8 passengers",
                    cargo = "84.3 cubic feet (max)",
                    driveType = "Available Dynamic Torque Vectoring AWD",
                    suspension = "Multi-link rear suspension",
                    brakes = "Power-assisted ventilated disc brakes",
                    wheels = "20-inch Platinum alloy wheels",
                    infotainment = "12.3-inch touchscreen with Apple CarPlay",
                    audio = "JBL Premium Audio with 11 speakers",
                    interior = "Leather-trimmed seats, tri-zone climate control",
                    safety = "Toyota Safety Sense 2.5+",
                    warranty = "36-month/36,000-mile basic warranty"
                ),
                ToyotaCar(
                    id = 4,
                    name = "2024 Toyota Tundra",
                    image = R.drawable.toyota_tundra_trd_pro,
                    price = "Starting at $39,965",
                    topTrim = "TRD Pro from $71,025",
                    lease = "$459/month for 36 months",
                    engine = "i-FORCE MAX 3.5L Twin-Turbo V6 Hybrid",
                    transmission = "10-speed automatic transmission",
                    acceleration = "0-60 mph in 5.7 seconds",
                    torque = "583 lb-ft @ 2,400 rpm",
                    fuelEfficiency = "20 city / 24 highway MPG",
                    fuelTank = "32.2 gallon fuel tank",
                    dimensions = "233.6\" L x 80.2\" W x 78.0\" H",
                    groundClearance = "10.9 inches",
                    seating = "5-6 passengers",
                    cargo = "65.6 cubic feet (bed)",
                    driveType = "Part-time 4WD with electronic transfer case",
                    suspension = "TRD Pro FOX shocks with remote reservoirs",
                    brakes = "Power-assisted ventilated disc brakes",
                    wheels = "18-inch TRD Pro BBS forged wheels",
                    infotainment = "14-inch touchscreen with Apple CarPlay",
                    audio = "JBL Premium Audio with 12 speakers",
                    interior = "TRD Pro leather-trimmed seats, dual-zone climate control",
                    safety = "Toyota Safety Sense 2.5",
                    warranty = "36-month/36,000-mile basic warranty"
                ),
                ToyotaCar(
                    id = 5,
                    name = "2024 Toyota Corolla",
                    image = R.drawable.toyota_corolla_se,
                    price = "Starting at $21,900",
                    topTrim = "XSE from $26,700",
                    lease = "$239/month for 36 months",
                    engine = "2.0L Dynamic Force 4-cylinder",
                    transmission = "Dynamic-Shift CVT",
                    acceleration = "0-60 mph in 7.8 seconds",
                    torque = "151 lb-ft @ 4,400 rpm",
                    fuelEfficiency = "31 city / 40 highway MPG",
                    fuelTank = "13.2 gallon fuel tank",
                    dimensions = "182.3\" L x 70.1\" W x 56.5\" H",
                    groundClearance = "5.3 inches",
                    seating = "5 passengers",
                    cargo = "13.1 cubic feet",
                    driveType = "Front-Wheel Drive (FWD)",
                    suspension = "Independent MacPherson strut",
                    brakes = "Power-assisted ventilated disc brakes",
                    wheels = "18-inch machined alloy wheels",
                    infotainment = "8-inch touchscreen with Apple CarPlay",
                    audio = "JBL Premium Audio with 8 speakers",
                    interior = "Sport SofTex®-trimmed seats, automatic climate control",
                    safety = "Toyota Safety Sense 3.0",
                    warranty = "36-month/36,000-mile basic warranty"
                )
            )
        }
    }
}